[package]
name = "rldd"
version = "0.4.0"
authors = [ "Adhemerval Zanella <zatrazz@gmail.com>" ]
edition = "2021"
license = "MIT"
description = """
A program to print shared object dependencies
"""
repository = "https://github.com/zatrazz/rldd/"
homepage = "https://github.com/zatrazz/rldd/"
readme = "README.md"
keywords = ["elf", "mach-o", "pe", "cli", ]
categories = ["command-line-utilities"]
exclude = [
    "TODO.md",
    "doc/screenshot.png",
]

[dependencies]
# There is no need for compression.
object = { version = "0.40.0", default-features = false, features = [ "read" ] }
memmap2 = "0.9.11"
glob = "0.3.4"
termcolor = "1.4.1"
argh = "0.1.19"

[target.'cfg(any(target_os = "macos", target_os = "android"))'.dependencies]
libc = "0.2.138"

[target.'cfg(all(target_os = "linux", any(target_arch = "x86", target_arch = "x86_64")))'.dependencies]
raw-cpuid = "11.6.0"

# The KnownDLLs registry key and the Windows directory.
[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_System_Registry",
    "Win32_System_SystemInformation",
] }

[target.'cfg(any(target_os = "android", target_os = "freebsd", windows))'.dev-dependencies]
tempfile = "3.3.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
# Defaultimproves compile times, but prevents some optimizations.
codegen-units = 1
# Remove stack unwinder and backtrace.
panic = "abort"
